---
inherit_gem:
  rubocop-fnando: .rubocop.yml

require:
  - rubocop-yard

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
    - test/fixtures/app/**/*
    - test/fixtures/sample_app/**/*
    - tmp/**/*

Lint/EmptyClass:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false

Minitest/NoAssertions:
  Exclude:
    - test/sequel/plugins/encrypted_attributes_test.rb

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Minitest/TestFileName:
  Exclude:
    - lib/**/*.rb

Minitest/NoTestCases:
  Exclude:
    - lib/**/*.rb

Minitest/EmptyLineBeforeAssertionMethods:
  Exclude:
    - lib/**/*.rb

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/zee/controller.rb
    - lib/zee/controller/**/*.rb
    - lib/zee/view_helpers/**/*.rb

Style/RedundantFetchBlock:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
