---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
    - test/fixtures/app/**/*

Naming/FileName:
  Exclude:
    - API_DESIGN.rb

Style/FetchEnvVar:
  Enabled: false
