#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/zee/cli"

if ARGV[0]&.include?(":")
  parts = ARGV.shift.split(":")
  ARGV.unshift(*parts)
end

# `run` is a reserved command in Thor, so we need to handle it specially.
ARGV[0] = "_run" if ARGV[0] == "run"

Zee::CLI.start
